    LIST P=16F877A
    #include <P16F877A.INC>
    __CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF
SLAVE_F0_ADDR   EQU 0x40
SLAVE_F1_ADDR   EQU 0x42
SLAVE_F2_ADDR   EQU 0x44
STATE_IDLE      EQU 0x00
STATE_UP        EQU 0x01
STATE_DOWN      EQU 0x02
STATE_DOOR_OPEN EQU 0x03
STATE_DOOR_CLOSE EQU 0x04
FLOOR_GF        EQU 0x00
FLOOR_1         EQU 0x01
FLOOR_2         EQU 0x02
CH_DOOR_CLOSED  EQU 0x00
CH_DOOR_OPEN    EQU 0x01
CH_IR_SENSOR    EQU 0x02
CH_OVERWEIGHT   EQU 0x03
CH_FLOOR_GF     EQU 0x04
CH_FLOOR_1      EQU 0x05
CH_FLOOR_2      EQU 0x06
CH_BTN_GF       EQU 0x07
CH_BTN_1        EQU 0x08
CH_BTN_2        EQU 0x09
CH_BTN_OPEN     EQU 0x0A
CH_BTN_CLOSE    EQU 0x0B
DELAY_2SEC      EQU 0xE0
BUZZER_TIME     EQU 0xF0
CMD_UPDATE_LCD  EQU 0x01
CMD_GET_BUTTONS EQU 0x02
    CBLOCK 0x20
        E1_STATE
        E1_CURRENT_FLOOR
        E1_TARGET_FLOOR
        E1_DIRECTION
        E1_REQUESTS_UP
        E1_REQUESTS_DN
        E1_CABIN_REQUESTS
        E1_SENSORS
        E1_FLOOR_SENSORS
        E1_BUZZER_TIMER
        E1_DOOR_TIMER
        E2_STATE
        E2_CURRENT_FLOOR
        E2_TARGET_FLOOR
        E2_DIRECTION
        E2_REQUESTS_UP
        E2_REQUESTS_DN
        E2_CABIN_REQUESTS
        E2_SENSORS
        E2_FLOOR_SENSORS
        E2_BUZZER_TIMER
        E2_DOOR_TIMER
        E3_STATE
        E3_CURRENT_FLOOR
        E3_TARGET_FLOOR
        E3_DIRECTION
        E3_REQUESTS_UP
        E3_REQUESTS_DN
        E3_CABIN_REQUESTS
        E3_SENSORS
        E3_FLOOR_SENSORS
        E3_BUZZER_TIMER
        E3_DOOR_TIMER
        F0_BUTTONS
        F1_BUTTONS
        F2_BUTTONS
        TEMP_REG
        TEMP_REG2
        MUX_CHANNEL
        CURRENT_ELEVATOR
        I2C_BUFFER
        I2C_ADDR
        DELAY_COUNT1
        DELAY_COUNT2
        DELAY_COUNT3
        SCAN_RESULT
        FLOOR_SERVICED
    ENDC
    ORG 0x0000
    GOTO    MAIN_INIT
    ORG 0x0004
    RETFIE

MAIN_INIT:
    BSF     STATUS, RP0
    BCF     STATUS, RP1
    MOVLW   0x07
    MOVWF   TRISA
    CLRF    TRISB
    MOVLW   0x18
    MOVWF   TRISC
    CLRF    TRISD
    CLRF    TRISE
    MOVLW   0x06
    MOVWF   ADCON1
    MOVLW   0x09
    MOVWF   SSPADD
    BCF     STATUS, RP0
    MOVLW   0x28
    MOVWF   SSPCON
    CLRF    PORTA
    CLRF    PORTB
    CLRF    PORTC
    CLRF    PORTD
    CLRF    PORTE
    BSF     PORTB, 4
    BSF     PORTB, 5
    BSF     PORTB, 6
    CALL    INIT_ELEVATORS
    BSF     INTCON, GIE
    BSF     INTCON, PEIE

MAIN_LOOP:
    CALL    SCAN_ALL_SENSORS
    CALL    GET_SLAVE_BUTTONS
    CALL    PROCESS_REQUESTS
    CALL    UPDATE_ELEVATOR_1
    CALL    UPDATE_ELEVATOR_2
    CALL    UPDATE_ELEVATOR_3
    CALL    HANDLE_DOORS
    CALL    UPDATE_BUZZERS
    CALL    SEND_LCD_UPDATES
    CALL    DELAY_10MS
    GOTO    MAIN_LOOP

INIT_ELEVATORS:
    MOVLW   STATE_IDLE
    MOVWF   E1_STATE
    MOVLW   FLOOR_GF
    MOVWF   E1_CURRENT_FLOOR
    CLRF    E1_TARGET_FLOOR
    CLRF    E1_DIRECTION
    CLRF    E1_REQUESTS_UP
    CLRF    E1_REQUESTS_DN
    CLRF    E1_CABIN_REQUESTS
    CLRF    E1_SENSORS
    CLRF    E1_FLOOR_SENSORS
    CLRF    E1_BUZZER_TIMER
    CLRF    E1_DOOR_TIMER
    MOVLW   STATE_IDLE
    MOVWF   E2_STATE
    MOVLW   FLOOR_1
    MOVWF   E2_CURRENT_FLOOR
    CLRF    E2_TARGET_FLOOR
    CLRF    E2_DIRECTION
    CLRF    E2_REQUESTS_UP
    CLRF    E2_REQUESTS_DN
    CLRF    E2_CABIN_REQUESTS
    CLRF    E2_SENSORS
    CLRF    E2_FLOOR_SENSORS
    CLRF    E2_BUZZER_TIMER
    CLRF    E2_DOOR_TIMER
    MOVLW   STATE_IDLE
    MOVWF   E3_STATE
    MOVLW   FLOOR_2
    MOVWF   E3_CURRENT_FLOOR
    CLRF    E3_TARGET_FLOOR
    CLRF    E3_DIRECTION
    CLRF    E3_REQUESTS_UP
    CLRF    E3_REQUESTS_DN
    CLRF    E3_CABIN_REQUESTS
    CLRF    E3_SENSORS
    CLRF    E3_FLOOR_SENSORS
    CLRF    E3_BUZZER_TIMER
    CLRF    E3_DOOR_TIMER
    CLRF    FLOOR_SERVICED
    CLRF    F0_BUTTONS
    CLRF    F1_BUTTONS
    CLRF    F2_BUTTONS
    RETURN

SCAN_ALL_SENSORS:
    MOVLW   0x01
    MOVWF   CURRENT_ELEVATOR
    CALL    SCAN_ELEVATOR_SENSORS
    MOVF    SCAN_RESULT, W
    MOVWF   E1_SENSORS
    CALL    SCAN_FLOOR_SENSORS
    MOVF    SCAN_RESULT, W
    MOVWF   E1_FLOOR_SENSORS
    CALL    SCAN_CABIN_BUTTONS
    MOVF    SCAN_RESULT, W
    IORWF   E1_CABIN_REQUESTS, F
    MOVLW   0x02
    MOVWF   CURRENT_ELEVATOR
    CALL    SCAN_ELEVATOR_SENSORS
    MOVF    SCAN_RESULT, W
    MOVWF   E2_SENSORS
    CALL    SCAN_FLOOR_SENSORS
    MOVF    SCAN_RESULT, W
    MOVWF   E2_FLOOR_SENSORS
    CALL    SCAN_CABIN_BUTTONS
    MOVF    SCAN_RESULT, W
    IORWF   E2_CABIN_REQUESTS, F
    MOVLW   0x03
    MOVWF   CURRENT_ELEVATOR
    CALL    SCAN_ELEVATOR_SENSORS
    MOVF    SCAN_RESULT, W
    MOVWF   E3_SENSORS
    CALL    SCAN_FLOOR_SENSORS
    MOVF    SCAN_RESULT, W
    MOVWF   E3_FLOOR_SENSORS
    CALL    SCAN_CABIN_BUTTONS
    MOVF    SCAN_RESULT, W
    IORWF   E3_CABIN_REQUESTS, F
    RETURN

SELECT_MUX:
    BSF     PORTB, 4
    BSF     PORTB, 5
    BSF     PORTB, 6
    MOVF    CURRENT_ELEVATOR, W
    SUBLW   0x01
    BTFSC   STATUS, Z
    BCF     PORTB, 4
    MOVF    CURRENT_ELEVATOR, W
    SUBLW   0x02
    BTFSC   STATUS, Z
    BCF     PORTB, 5
    MOVF    CURRENT_ELEVATOR, W
    SUBLW   0x03
    BTFSC   STATUS, Z
    BCF     PORTB, 6
    RETURN

SET_MUX_CHANNEL:
    MOVF    MUX_CHANNEL, W
    ANDLW   0x0F
    MOVWF   TEMP_REG
    MOVF    PORTB, W
    ANDLW   0xF0
    IORWF   TEMP_REG, W
    MOVWF   PORTB
    CALL    DELAY_50US
    RETURN

READ_MUX_OUTPUT:
    MOVF    CURRENT_ELEVATOR, W
    SUBLW   0x01
    BTFSC   STATUS, Z
    GOTO    READ_RA0
    MOVF    CURRENT_ELEVATOR, W
    SUBLW   0x02
    BTFSC   STATUS, Z
    GOTO    READ_RA1
    GOTO    READ_RA2
READ_RA0:
    BTFSC   PORTA, 0
    RETLW   0x01
    RETLW   0x00
READ_RA1:
    BTFSC   PORTA, 1
    RETLW   0x01
    RETLW   0x00
READ_RA2:
    BTFSC   PORTA, 2
    RETLW   0x01
    RETLW   0x00

SCAN_ELEVATOR_SENSORS:
    CALL    SELECT_MUX
    CLRF    SCAN_RESULT
    MOVLW   CH_DOOR_CLOSED
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 0
    MOVLW   CH_DOOR_OPEN
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 1
    MOVLW   CH_IR_SENSOR
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 2
    MOVLW   CH_OVERWEIGHT
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 3
    RETURN

SCAN_FLOOR_SENSORS:
    CALL    SELECT_MUX
    CLRF    SCAN_RESULT
    MOVLW   CH_FLOOR_GF
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 0
    MOVLW   CH_FLOOR_1
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 1
    MOVLW   CH_FLOOR_2
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 2
    RETURN

SCAN_CABIN_BUTTONS:
    CALL    SELECT_MUX
    CLRF    SCAN_RESULT
    MOVLW   CH_BTN_GF
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 0
    MOVLW   CH_BTN_1
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 1
    MOVLW   CH_BTN_2
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 2
    MOVLW   CH_BTN_OPEN
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 3
    MOVLW   CH_BTN_CLOSE
    MOVWF   MUX_CHANNEL
    CALL    SET_MUX_CHANNEL
    CALL    READ_MUX_OUTPUT
    BTFSS   STATUS, Z
    BSF     SCAN_RESULT, 4
    RETURN

I2C_START_COND:
    BSF     STATUS, RP0
    BSF     SSPCON2, SEN
    BCF     STATUS, RP0
I2C_START_W:
    BSF     STATUS, RP0
    BTFSC   SSPCON2, SEN
    GOTO    I2C_START_W
    BCF     STATUS, RP0
    RETURN

I2C_STOP_COND:
    BSF     STATUS, RP0
    BSF     SSPCON2, PEN
    BCF     STATUS, RP0
I2C_STOP_W:
    BSF     STATUS, RP0
    BTFSC   SSPCON2, PEN
    GOTO    I2C_STOP_W
    BCF     STATUS, RP0
    RETURN

I2C_RESTART_COND:
    BSF     STATUS, RP0
    BSF     SSPCON2, RSEN
    BCF     STATUS, RP0
I2C_RESTART_W:
    BSF     STATUS, RP0
    BTFSC   SSPCON2, RSEN
    GOTO    I2C_RESTART_W
    BCF     STATUS, RP0
    RETURN

I2C_WRITE_BYTE:
    BCF     STATUS, RP0
    MOVF    I2C_BUFFER, W
    MOVWF   SSPBUF
I2C_WRITE_W:
    BSF     STATUS, RP0
    BTFSC   SSPSTAT, R_W
    GOTO    I2C_WRITE_W
    BCF     STATUS, RP0
    RETURN

I2C_READ_BYTE:
    BSF     STATUS, RP0
    BSF     SSPCON2, RCEN
    BCF     STATUS, RP0
I2C_READ_W:
    BSF     STATUS, RP0
    BTFSC   SSPCON2, RCEN
    GOTO    I2C_READ_W
    BCF     STATUS, RP0
    MOVF    SSPBUF, W
    MOVWF   I2C_BUFFER
    RETURN

I2C_SEND_NACK:
    BSF     STATUS, RP0
    BSF     SSPCON2, ACKDT
    BSF     SSPCON2, ACKEN
    BCF     STATUS, RP0
I2C_NACK_W:
    BSF     STATUS, RP0
    BTFSC   SSPCON2, ACKEN
    GOTO    I2C_NACK_W
    BCF     STATUS, RP0
    RETURN

GET_SLAVE_BUTTONS:
    MOVLW   SLAVE_F0_ADDR
    MOVWF   I2C_ADDR
    CALL    READ_SLAVE_BTN
    MOVF    I2C_BUFFER, W
    MOVWF   F0_BUTTONS
    MOVLW   SLAVE_F1_ADDR
    MOVWF   I2C_ADDR
    CALL    READ_SLAVE_BTN
    MOVF    I2C_BUFFER, W
    MOVWF   F1_BUTTONS
    MOVLW   SLAVE_F2_ADDR
    MOVWF   I2C_ADDR
    CALL    READ_SLAVE_BTN
    MOVF    I2C_BUFFER, W
    MOVWF   F2_BUTTONS
    RETURN

READ_SLAVE_BTN:
    CALL    I2C_START_COND
    MOVF    I2C_ADDR, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVLW   CMD_GET_BUTTONS
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    CALL    I2C_RESTART_COND
    MOVF    I2C_ADDR, W
    IORLW   0x01
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    CALL    I2C_READ_BYTE
    CALL    I2C_SEND_NACK
    CALL    I2C_STOP_COND
    RETURN

SEND_LCD_UPDATES:
    MOVLW   SLAVE_F0_ADDR
    MOVWF   I2C_ADDR
    CALL    SEND_LCD_SLAVE
    MOVLW   SLAVE_F1_ADDR
    MOVWF   I2C_ADDR
    CALL    SEND_LCD_SLAVE
    MOVLW   SLAVE_F2_ADDR
    MOVWF   I2C_ADDR
    CALL    SEND_LCD_SLAVE
    RETURN

SEND_LCD_SLAVE:
    CALL    I2C_START_COND
    MOVF    I2C_ADDR, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVLW   CMD_UPDATE_LCD
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVF    E1_STATE, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVF    E1_CURRENT_FLOOR, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVF    E1_DIRECTION, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVF    E2_STATE, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVF    E2_CURRENT_FLOOR, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVF    E2_DIRECTION, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVF    E3_STATE, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVF    E3_CURRENT_FLOOR, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    MOVF    E3_DIRECTION, W
    MOVWF   I2C_BUFFER
    CALL    I2C_WRITE_BYTE
    CALL    I2C_STOP_COND
    RETURN

PROCESS_REQUESTS:
    CALL    PROCESS_F0_REQ
    CALL    PROCESS_F1_REQ
    CALL    PROCESS_F2_REQ
    RETURN

PROCESS_F0_REQ:
    BTFSS   F0_BUTTONS, 0
    GOTO    CHK_F0_STAFF
    BTFSC   FLOOR_SERVICED, 0
    GOTO    CHK_F0_STAFF
    CALL    ASSIGN_PUB_UP_F0
CHK_F0_STAFF:
    BTFSS   F0_BUTTONS, 4
    RETURN
    BTFSS   F0_BUTTONS, 2
    RETURN
    BSF     E3_REQUESTS_UP, 0
    RETURN

PROCESS_F1_REQ:
    BTFSS   F1_BUTTONS, 0
    GOTO    CHK_F1_DN
    BTFSC   FLOOR_SERVICED, 1
    GOTO    CHK_F1_DN
    CALL    ASSIGN_PUB_UP_F1
CHK_F1_DN:
    BTFSS   F1_BUTTONS, 1
    GOTO    CHK_F1_STAFF
    BTFSC   FLOOR_SERVICED, 1
    GOTO    CHK_F1_STAFF
    CALL    ASSIGN_PUB_DN_F1
CHK_F1_STAFF:
    BTFSS   F1_BUTTONS, 4
    RETURN
    BTFSC   F1_BUTTONS, 2
    BSF     E3_REQUESTS_UP, 1
    BTFSC   F1_BUTTONS, 3
    BSF     E3_REQUESTS_DN, 1
    RETURN

PROCESS_F2_REQ:
    BTFSS   F2_BUTTONS, 1
    GOTO    CHK_F2_STAFF
    BTFSC   FLOOR_SERVICED, 2
    GOTO    CHK_F2_STAFF
    CALL    ASSIGN_PUB_DN_F2
CHK_F2_STAFF:
    BTFSS   F2_BUTTONS, 4
    RETURN
    BTFSS   F2_BUTTONS, 3
    RETURN
    BSF     E3_REQUESTS_DN, 2
    RETURN

ASSIGN_PUB_UP_F0:
    MOVF    E1_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    ASGN_E1_F0
    MOVF    E2_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    ASGN_E2_F0
    GOTO    ASGN_E1_F0
ASGN_E1_F0:
    BSF     E1_REQUESTS_UP, 0
    BSF     FLOOR_SERVICED, 0
    RETURN
ASGN_E2_F0:
    BSF     E2_REQUESTS_UP, 0
    BSF     FLOOR_SERVICED, 0
    RETURN

ASSIGN_PUB_UP_F1:
    MOVF    E1_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    ASGN_E1_F1_UP
    MOVF    E2_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    ASGN_E2_F1_UP
    GOTO    ASGN_E1_F1_UP
ASGN_E1_F1_UP:
    BSF     E1_REQUESTS_UP, 1
    BSF     FLOOR_SERVICED, 1
    RETURN
ASGN_E2_F1_UP:
    BSF     E2_REQUESTS_UP, 1
    BSF     FLOOR_SERVICED, 1
    RETURN

ASSIGN_PUB_DN_F1:
    MOVF    E1_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    ASGN_E1_F1_DN
    MOVF    E2_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    ASGN_E2_F1_DN
    GOTO    ASGN_E1_F1_DN
ASGN_E1_F1_DN:
    BSF     E1_REQUESTS_DN, 1
    BSF     FLOOR_SERVICED, 1
    RETURN
ASGN_E2_F1_DN:
    BSF     E2_REQUESTS_DN, 1
    BSF     FLOOR_SERVICED, 1
    RETURN

ASSIGN_PUB_DN_F2:
    MOVF    E1_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    ASGN_E1_F2_DN
    MOVF    E2_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    ASGN_E2_F2_DN
    GOTO    ASGN_E1_F2_DN
ASGN_E1_F2_DN:
    BSF     E1_REQUESTS_DN, 2
    BSF     FLOOR_SERVICED, 2
    RETURN
ASGN_E2_F2_DN:
    BSF     E2_REQUESTS_DN, 2
    BSF     FLOOR_SERVICED, 2
    RETURN

UPDATE_ELEVATOR_1:
    BTFSC   E1_FLOOR_SENSORS, 0
    CLRF    E1_CURRENT_FLOOR
    BTFSC   E1_FLOOR_SENSORS, 1
    MOVLW   FLOOR_1
    BTFSC   E1_FLOOR_SENSORS, 1
    MOVWF   E1_CURRENT_FLOOR
    BTFSC   E1_FLOOR_SENSORS, 2
    MOVLW   FLOOR_2
    BTFSC   E1_FLOOR_SENSORS, 2
    MOVWF   E1_CURRENT_FLOOR
    MOVF    E1_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    E1_IDLE_H
    MOVF    E1_STATE, W
    SUBLW   STATE_UP
    BTFSC   STATUS, Z
    GOTO    E1_UP_H
    MOVF    E1_STATE, W
    SUBLW   STATE_DOWN
    BTFSC   STATUS, Z
    GOTO    E1_DOWN_H
    RETURN

E1_IDLE_H:
    MOVF    E1_REQUESTS_UP, W
    IORWF   E1_REQUESTS_DN, W
    MOVWF   TEMP_REG
    MOVF    E1_CABIN_REQUESTS, W
    ANDLW   0x07
    IORWF   TEMP_REG, W
    BTFSC   STATUS, Z
    RETURN
    CALL    FIND_E1_TGT
    MOVF    E1_TARGET_FLOOR, W
    SUBWF   E1_CURRENT_FLOOR, W
    BTFSC   STATUS, Z
    GOTO    E1_AT_TGT
    BTFSS   STATUS, C
    GOTO    E1_GO_UP
    GOTO    E1_GO_DN

E1_GO_UP:
    MOVLW   STATE_UP
    MOVWF   E1_STATE
    MOVWF   E1_DIRECTION
    BSF     PORTD, 0
    BCF     PORTD, 1
    RETURN

E1_GO_DN:
    MOVLW   STATE_DOWN
    MOVWF   E1_STATE
    MOVWF   E1_DIRECTION
    BCF     PORTD, 0
    BSF     PORTD, 1
    RETURN

E1_AT_TGT:
    CALL    CLR_E1_REQ
    MOVF    E1_CURRENT_FLOOR, W
    CALL    CLR_FLR_SVC
    MOVLW   BUZZER_TIME
    MOVWF   E1_BUZZER_TIMER
    BSF     PORTD, 4
    MOVLW   DELAY_2SEC
    MOVWF   E1_DOOR_TIMER
    MOVLW   STATE_DOOR_OPEN
    MOVWF   E1_STATE
    RETURN

E1_UP_H:
    MOVF    E1_FLOOR_SENSORS, W
    BTFSC   STATUS, Z
    RETURN
    BTFSS   E1_FLOOR_SENSORS, 0
    GOTO    E1_UP_C1
    BTFSC   E1_REQUESTS_UP, 0
    GOTO    E1_STOP
    BTFSC   E1_CABIN_REQUESTS, 0
    GOTO    E1_STOP
E1_UP_C1:
    BTFSS   E1_FLOOR_SENSORS, 1
    GOTO    E1_UP_C2
    BTFSC   E1_REQUESTS_UP, 1
    GOTO    E1_STOP
    BTFSC   E1_CABIN_REQUESTS, 1
    GOTO    E1_STOP
E1_UP_C2:
    BTFSS   E1_FLOOR_SENSORS, 2
    RETURN
    BTFSC   E1_CABIN_REQUESTS, 2
    GOTO    E1_STOP
    BTFSC   E1_REQUESTS_UP, 2
    GOTO    E1_STOP
    MOVF    E1_REQUESTS_DN, W
    BTFSS   STATUS, Z
    GOTO    E1_REV_DN
    GOTO    E1_STOP

E1_STOP:
    BCF     PORTD, 0
    BCF     PORTD, 1
    CALL    CLR_E1_REQ
    MOVF    E1_CURRENT_FLOOR, W
    CALL    CLR_FLR_SVC
    MOVLW   BUZZER_TIME
    MOVWF   E1_BUZZER_TIMER
    BSF     PORTD, 4
    MOVLW   DELAY_2SEC
    MOVWF   E1_DOOR_TIMER
    MOVLW   STATE_DOOR_OPEN
    MOVWF   E1_STATE
    RETURN

E1_REV_DN:
    MOVLW   STATE_DOWN
    MOVWF   E1_STATE
    MOVWF   E1_DIRECTION
    BCF     PORTD, 0
    BSF     PORTD, 1
    RETURN

E1_DOWN_H:
    MOVF    E1_FLOOR_SENSORS, W
    BTFSC   STATUS, Z
    RETURN
    BTFSS   E1_FLOOR_SENSORS, 2
    GOTO    E1_DN_C1
    BTFSC   E1_REQUESTS_DN, 2
    GOTO    E1_STOP
    BTFSC   E1_CABIN_REQUESTS, 2
    GOTO    E1_STOP
E1_DN_C1:
    BTFSS   E1_FLOOR_SENSORS, 1
    GOTO    E1_DN_C0
    BTFSC   E1_REQUESTS_DN, 1
    GOTO    E1_STOP
    BTFSC   E1_CABIN_REQUESTS, 1
    GOTO    E1_STOP
E1_DN_C0:
    BTFSS   E1_FLOOR_SENSORS, 0
    RETURN
    BTFSC   E1_CABIN_REQUESTS, 0
    GOTO    E1_STOP
    BTFSC   E1_REQUESTS_DN, 0
    GOTO    E1_STOP
    MOVF    E1_REQUESTS_UP, W
    BTFSS   STATUS, Z
    GOTO    E1_REV_UP
    GOTO    E1_STOP

E1_REV_UP:
    MOVLW   STATE_UP
    MOVWF   E1_STATE
    MOVWF   E1_DIRECTION
    BSF     PORTD, 0
    BCF     PORTD, 1
    RETURN

FIND_E1_TGT:
    BTFSC   E1_REQUESTS_UP, 0
    GOTO    E1_TGT_GF
    BTFSC   E1_REQUESTS_UP, 1
    GOTO    E1_TGT_F1
    BTFSC   E1_REQUESTS_UP, 2
    GOTO    E1_TGT_F2
    BTFSC   E1_CABIN_REQUESTS, 0
    GOTO    E1_TGT_GF
    BTFSC   E1_CABIN_REQUESTS, 1
    GOTO    E1_TGT_F1
    BTFSC   E1_CABIN_REQUESTS, 2
    GOTO    E1_TGT_F2
    BTFSC   E1_REQUESTS_DN, 2
    GOTO    E1_TGT_F2
    BTFSC   E1_REQUESTS_DN, 1
    GOTO    E1_TGT_F1
    BTFSC   E1_REQUESTS_DN, 0
    GOTO    E1_TGT_GF
    RETURN
E1_TGT_GF:
    CLRF    E1_TARGET_FLOOR
    RETURN
E1_TGT_F1:
    MOVLW   FLOOR_1
    MOVWF   E1_TARGET_FLOOR
    RETURN
E1_TGT_F2:
    MOVLW   FLOOR_2
    MOVWF   E1_TARGET_FLOOR
    RETURN

CLR_E1_REQ:
    MOVF    E1_CURRENT_FLOOR, W
    BTFSC   STATUS, Z
    GOTO    CLR_E1_GF
    SUBLW   FLOOR_1
    BTFSC   STATUS, Z
    GOTO    CLR_E1_F1
    GOTO    CLR_E1_F2
CLR_E1_GF:
    BCF     E1_REQUESTS_UP, 0
    BCF     E1_REQUESTS_DN, 0
    BCF     E1_CABIN_REQUESTS, 0
    RETURN
CLR_E1_F1:
    BCF     E1_REQUESTS_UP, 1
    BCF     E1_REQUESTS_DN, 1
    BCF     E1_CABIN_REQUESTS, 1
    RETURN
CLR_E1_F2:
    BCF     E1_REQUESTS_UP, 2
    BCF     E1_REQUESTS_DN, 2
    BCF     E1_CABIN_REQUESTS, 2
    RETURN

CLR_FLR_SVC:
    MOVWF   TEMP_REG
    MOVF    TEMP_REG, W
    BTFSC   STATUS, Z
    BCF     FLOOR_SERVICED, 0
    MOVF    TEMP_REG, W
    SUBLW   FLOOR_1
    BTFSC   STATUS, Z
    BCF     FLOOR_SERVICED, 1
    MOVF    TEMP_REG, W
    SUBLW   FLOOR_2
    BTFSC   STATUS, Z
    BCF     FLOOR_SERVICED, 2
    RETURN

UPDATE_ELEVATOR_2:
    BTFSC   E2_FLOOR_SENSORS, 0
    CLRF    E2_CURRENT_FLOOR
    BTFSC   E2_FLOOR_SENSORS, 1
    MOVLW   FLOOR_1
    BTFSC   E2_FLOOR_SENSORS, 1
    MOVWF   E2_CURRENT_FLOOR
    BTFSC   E2_FLOOR_SENSORS, 2
    MOVLW   FLOOR_2
    BTFSC   E2_FLOOR_SENSORS, 2
    MOVWF   E2_CURRENT_FLOOR
    MOVF    E2_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    E2_IDLE_H
    MOVF    E2_STATE, W
    SUBLW   STATE_UP
    BTFSC   STATUS, Z
    GOTO    E2_UP_H
    MOVF    E2_STATE, W
    SUBLW   STATE_DOWN
    BTFSC   STATUS, Z
    GOTO    E2_DOWN_H
    RETURN

E2_IDLE_H:
    MOVF    E2_REQUESTS_UP, W
    IORWF   E2_REQUESTS_DN, W
    MOVWF   TEMP_REG
    MOVF    E2_CABIN_REQUESTS, W
    ANDLW   0x07
    IORWF   TEMP_REG, W
    BTFSC   STATUS, Z
    RETURN
    CALL    FIND_E2_TGT
    MOVF    E2_TARGET_FLOOR, W
    SUBWF   E2_CURRENT_FLOOR, W
    BTFSC   STATUS, Z
    GOTO    E2_AT_TGT
    BTFSS   STATUS, C
    GOTO    E2_GO_UP
    GOTO    E2_GO_DN

E2_GO_UP:
    MOVLW   STATE_UP
    MOVWF   E2_STATE
    MOVWF   E2_DIRECTION
    BSF     PORTD, 5
    BCF     PORTD, 6
    RETURN

E2_GO_DN:
    MOVLW   STATE_DOWN
    MOVWF   E2_STATE
    MOVWF   E2_DIRECTION
    BCF     PORTD, 5
    BSF     PORTD, 6
    RETURN

E2_AT_TGT:
    CALL    CLR_E2_REQ
    MOVF    E2_CURRENT_FLOOR, W
    CALL    CLR_FLR_SVC
    MOVLW   BUZZER_TIME
    MOVWF   E2_BUZZER_TIMER
    BSF     PORTE, 1
    MOVLW   DELAY_2SEC
    MOVWF   E2_DOOR_TIMER
    MOVLW   STATE_DOOR_OPEN
    MOVWF   E2_STATE
    RETURN

E2_UP_H:
    MOVF    E2_FLOOR_SENSORS, W
    BTFSC   STATUS, Z
    RETURN
    BTFSS   E2_FLOOR_SENSORS, 0
    GOTO    E2_UP_C1
    BTFSC   E2_REQUESTS_UP, 0
    GOTO    E2_STOP
    BTFSC   E2_CABIN_REQUESTS, 0
    GOTO    E2_STOP
E2_UP_C1:
    BTFSS   E2_FLOOR_SENSORS, 1
    GOTO    E2_UP_C2
    BTFSC   E2_REQUESTS_UP, 1
    GOTO    E2_STOP
    BTFSC   E2_CABIN_REQUESTS, 1
    GOTO    E2_STOP
E2_UP_C2:
    BTFSS   E2_FLOOR_SENSORS, 2
    RETURN
    BTFSC   E2_CABIN_REQUESTS, 2
    GOTO    E2_STOP
    BTFSC   E2_REQUESTS_UP, 2
    GOTO    E2_STOP
    MOVF    E2_REQUESTS_DN, W
    BTFSS   STATUS, Z
    GOTO    E2_REV_DN
    GOTO    E2_STOP

E2_STOP:
    BCF     PORTD, 5
    BCF     PORTD, 6
    CALL    CLR_E2_REQ
    MOVF    E2_CURRENT_FLOOR, W
    CALL    CLR_FLR_SVC
    MOVLW   BUZZER_TIME
    MOVWF   E2_BUZZER_TIMER
    BSF     PORTE, 1
    MOVLW   DELAY_2SEC
    MOVWF   E2_DOOR_TIMER
    MOVLW   STATE_DOOR_OPEN
    MOVWF   E2_STATE
    RETURN

E2_REV_DN:
    MOVLW   STATE_DOWN
    MOVWF   E2_STATE
    MOVWF   E2_DIRECTION
    BCF     PORTD, 5
    BSF     PORTD, 6
    RETURN

E2_DOWN_H:
    MOVF    E2_FLOOR_SENSORS, W
    BTFSC   STATUS, Z
    RETURN
    BTFSS   E2_FLOOR_SENSORS, 2
    GOTO    E2_DN_C1
    BTFSC   E2_REQUESTS_DN, 2
    GOTO    E2_STOP
    BTFSC   E2_CABIN_REQUESTS, 2
    GOTO    E2_STOP
E2_DN_C1:
    BTFSS   E2_FLOOR_SENSORS, 1
    GOTO    E2_DN_C0
    BTFSC   E2_REQUESTS_DN, 1
    GOTO    E2_STOP
    BTFSC   E2_CABIN_REQUESTS, 1
    GOTO    E2_STOP
E2_DN_C0:
    BTFSS   E2_FLOOR_SENSORS, 0
    RETURN
    BTFSC   E2_CABIN_REQUESTS, 0
    GOTO    E2_STOP
    BTFSC   E2_REQUESTS_DN, 0
    GOTO    E2_STOP
    MOVF    E2_REQUESTS_UP, W
    BTFSS   STATUS, Z
    GOTO    E2_REV_UP
    GOTO    E2_STOP

E2_REV_UP:
    MOVLW   STATE_UP
    MOVWF   E2_STATE
    MOVWF   E2_DIRECTION
    BSF     PORTD, 5
    BCF     PORTD, 6
    RETURN

FIND_E2_TGT:
    BTFSC   E2_REQUESTS_UP, 0
    GOTO    E2_TGT_GF
    BTFSC   E2_REQUESTS_UP, 1
    GOTO    E2_TGT_F1
    BTFSC   E2_REQUESTS_UP, 2
    GOTO    E2_TGT_F2
    BTFSC   E2_CABIN_REQUESTS, 0
    GOTO    E2_TGT_GF
    BTFSC   E2_CABIN_REQUESTS, 1
    GOTO    E2_TGT_F1
    BTFSC   E2_CABIN_REQUESTS, 2
    GOTO    E2_TGT_F2
    BTFSC   E2_REQUESTS_DN, 2
    GOTO    E2_TGT_F2
    BTFSC   E2_REQUESTS_DN, 1
    GOTO    E2_TGT_F1
    BTFSC   E2_REQUESTS_DN, 0
    GOTO    E2_TGT_GF
    RETURN
E2_TGT_GF:
    CLRF    E2_TARGET_FLOOR
    RETURN
E2_TGT_F1:
    MOVLW   FLOOR_1
    MOVWF   E2_TARGET_FLOOR
    RETURN
E2_TGT_F2:
    MOVLW   FLOOR_2
    MOVWF   E2_TARGET_FLOOR
    RETURN

CLR_E2_REQ:
    MOVF    E2_CURRENT_FLOOR, W
    BTFSC   STATUS, Z
    GOTO    CLR_E2_GF
    SUBLW   FLOOR_1
    BTFSC   STATUS, Z
    GOTO    CLR_E2_F1
    GOTO    CLR_E2_F2
CLR_E2_GF:
    BCF     E2_REQUESTS_UP, 0
    BCF     E2_REQUESTS_DN, 0
    BCF     E2_CABIN_REQUESTS, 0
    RETURN
CLR_E2_F1:
    BCF     E2_REQUESTS_UP, 1
    BCF     E2_REQUESTS_DN, 1
    BCF     E2_CABIN_REQUESTS, 1
    RETURN
CLR_E2_F2:
    BCF     E2_REQUESTS_UP, 2
    BCF     E2_REQUESTS_DN, 2
    BCF     E2_CABIN_REQUESTS, 2
    RETURN

UPDATE_ELEVATOR_3:
    BTFSC   E3_FLOOR_SENSORS, 0
    CLRF    E3_CURRENT_FLOOR
    BTFSC   E3_FLOOR_SENSORS, 1
    MOVLW   FLOOR_1
    BTFSC   E3_FLOOR_SENSORS, 1
    MOVWF   E3_CURRENT_FLOOR
    BTFSC   E3_FLOOR_SENSORS, 2
    MOVLW   FLOOR_2
    BTFSC   E3_FLOOR_SENSORS, 2
    MOVWF   E3_CURRENT_FLOOR

    MOVF    E3_STATE, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    E3_IDLE_H
    MOVF    E3_STATE, W
    SUBLW   STATE_UP
    BTFSC   STATUS, Z
    GOTO    E3_UP_H
    MOVF    E3_STATE, W
    SUBLW   STATE_DOWN
    BTFSC   STATUS, Z
    GOTO    E3_DOWN_H
    RETURN

E3_IDLE_H:
    MOVF    E3_REQUESTS_UP, W
    IORWF   E3_REQUESTS_DN, W
    MOVWF   TEMP_REG
    MOVF    E3_CABIN_REQUESTS, W
    ANDLW   0x07
    IORWF   TEMP_REG, W
    BTFSC   STATUS, Z
    RETURN
    CALL    FIND_E3_TGT
    MOVF    E3_TARGET_FLOOR, W
    SUBWF   E3_CURRENT_FLOOR, W
    BTFSC   STATUS, Z
    GOTO    E3_AT_TGT
    BTFSS   STATUS, C
    GOTO    E3_GO_UP
    GOTO    E3_GO_DN

E3_GO_UP:
    MOVLW   STATE_UP
    MOVWF   E3_STATE
    MOVWF   E3_DIRECTION
    BSF     PORTD, 2
    BCF     PORTD, 3
    RETURN

E3_GO_DN:
    MOVLW   STATE_DOWN
    MOVWF   E3_STATE
    MOVWF   E3_DIRECTION
    BCF     PORTD, 2
    BSF     PORTD, 3
    RETURN

E3_AT_TGT:
    CALL    CLR_E3_REQ
    MOVLW   BUZZER_TIME
    MOVWF   E3_BUZZER_TIMER
    BSF     PORTC, 5
    MOVLW   DELAY_2SEC
    MOVWF   E3_DOOR_TIMER
    MOVLW   STATE_DOOR_OPEN
    MOVWF   E3_STATE
    RETURN

E3_UP_H:
    MOVF    E3_FLOOR_SENSORS, W
    BTFSC   STATUS, Z
    RETURN
    BTFSS   E3_FLOOR_SENSORS, 0
    GOTO    E3_UP_C1
    BTFSC   E3_REQUESTS_UP, 0
    GOTO    E3_STOP
    BTFSC   E3_CABIN_REQUESTS, 0
    GOTO    E3_STOP
E3_UP_C1:
    BTFSS   E3_FLOOR_SENSORS, 1
    GOTO    E3_UP_C2
    BTFSC   E3_REQUESTS_UP, 1
    GOTO    E3_STOP
    BTFSC   E3_CABIN_REQUESTS, 1
    GOTO    E3_STOP
E3_UP_C2:
    BTFSS   E3_FLOOR_SENSORS, 2
    RETURN
    BTFSC   E3_CABIN_REQUESTS, 2
    GOTO    E3_STOP
    BTFSC   E3_REQUESTS_UP, 2
    GOTO    E3_STOP
    MOVF    E3_REQUESTS_DN, W
    BTFSS   STATUS, Z
    GOTO    E3_REV_DN
    GOTO    E3_STOP

E3_STOP:
    BCF     PORTD, 2
    BCF     PORTD, 3
    CALL    CLR_E3_REQ
    MOVLW   BUZZER_TIME
    MOVWF   E3_BUZZER_TIMER
    BSF     PORTC, 5
    MOVLW   DELAY_2SEC
    MOVWF   E3_DOOR_TIMER
    MOVLW   STATE_DOOR_OPEN
    MOVWF   E3_STATE
    RETURN

E3_REV_DN:
    MOVLW   STATE_DOWN
    MOVWF   E3_STATE
    MOVWF   E3_DIRECTION
    BCF     PORTD, 2
    BSF     PORTD, 3
    RETURN

E3_DOWN_H:
    MOVF    E3_FLOOR_SENSORS, W
    BTFSC   STATUS, Z
    RETURN
    BTFSS   E3_FLOOR_SENSORS, 2
    GOTO    E3_DN_C1
    BTFSC   E3_REQUESTS_DN, 2
    GOTO    E3_STOP
    BTFSC   E3_CABIN_REQUESTS, 2
    GOTO    E3_STOP
E3_DN_C1:
    BTFSS   E3_FLOOR_SENSORS, 1
    GOTO    E3_DN_C0
    BTFSC   E3_REQUESTS_DN, 1
    GOTO    E3_STOP
    BTFSC   E3_CABIN_REQUESTS, 1
    GOTO    E3_STOP
E3_DN_C0:
    BTFSS   E3_FLOOR_SENSORS, 0
    RETURN
    BTFSC   E3_CABIN_REQUESTS, 0
    GOTO    E3_STOP
    BTFSC   E3_REQUESTS_DN, 0
    GOTO    E3_STOP
    MOVF    E3_REQUESTS_UP, W
    BTFSS   STATUS, Z
    GOTO    E3_REV_UP
    GOTO    E3_STOP

E3_REV_UP:
    MOVLW   STATE_UP
    MOVWF   E3_STATE
    MOVWF   E3_DIRECTION
    BSF     PORTD, 2
    BCF     PORTD, 3
    RETURN

FIND_E3_TGT:
    BTFSC   E3_REQUESTS_UP, 0
    GOTO    E3_TGT_GF
    BTFSC   E3_REQUESTS_UP, 1
    GOTO    E3_TGT_F1
    BTFSC   E3_REQUESTS_UP, 2
    GOTO    E3_TGT_F2
    BTFSC   E3_CABIN_REQUESTS, 0
    GOTO    E3_TGT_GF
    BTFSC   E3_CABIN_REQUESTS, 1
    GOTO    E3_TGT_F1
    BTFSC   E3_CABIN_REQUESTS, 2
    GOTO    E3_TGT_F2
    BTFSC   E3_REQUESTS_DN, 2
    GOTO    E3_TGT_F2
    BTFSC   E3_REQUESTS_DN, 1
    GOTO    E3_TGT_F1
    BTFSC   E3_REQUESTS_DN, 0
    GOTO    E3_TGT_GF
    RETURN
E3_TGT_GF:
    CLRF    E3_TARGET_FLOOR
    RETURN
E3_TGT_F1:
    MOVLW   FLOOR_1
    MOVWF   E3_TARGET_FLOOR
    RETURN
E3_TGT_F2:
    MOVLW   FLOOR_2
    MOVWF   E3_TARGET_FLOOR
    RETURN

CLR_E3_REQ:
    MOVF    E3_CURRENT_FLOOR, W
    BTFSC   STATUS, Z
    GOTO    CLR_E3_GF
    SUBLW   FLOOR_1
    BTFSC   STATUS, Z
    GOTO    CLR_E3_F1
    GOTO    CLR_E3_F2
CLR_E3_GF:
    BCF     E3_REQUESTS_UP, 0
    BCF     E3_REQUESTS_DN, 0
    BCF     E3_CABIN_REQUESTS, 0
    RETURN
CLR_E3_F1:
    BCF     E3_REQUESTS_UP, 1
    BCF     E3_REQUESTS_DN, 1
    BCF     E3_CABIN_REQUESTS, 1
    RETURN
CLR_E3_F2:
    BCF     E3_REQUESTS_UP, 2
    BCF     E3_REQUESTS_DN, 2
    BCF     E3_CABIN_REQUESTS, 2
    RETURN

HANDLE_DOORS:
    CALL    HANDLE_E1_DR
    CALL    HANDLE_E2_DR
    CALL    HANDLE_E3_DR
    RETURN

HANDLE_E1_DR:
    MOVF    E1_STATE, W
    SUBLW   STATE_DOOR_OPEN
    BTFSS   STATUS, Z
    GOTO    E1_CHK_CLS
    BTFSC   E1_SENSORS, 3
    GOTO    E1_OW
    BTFSC   E1_SENSORS, 2
    GOTO    E1_IR
    MOVF    E1_CABIN_REQUESTS, W
    ANDLW   0x08
    BTFSS   STATUS, Z
    GOTO    E1_KEEP_OP
    MOVF    E1_DOOR_TIMER, F
    BTFSC   STATUS, Z
    GOTO    E1_BGN_CLS
    DECF    E1_DOOR_TIMER, F
    RETURN
E1_OW:
    BSF     PORTD, 4
    MOVLW   DELAY_2SEC
    MOVWF   E1_DOOR_TIMER
    RETURN
E1_IR:
    MOVLW   DELAY_2SEC
    MOVWF   E1_DOOR_TIMER
    RETURN
E1_KEEP_OP:
    MOVLW   DELAY_2SEC
    MOVWF   E1_DOOR_TIMER
    RETURN
E1_BGN_CLS:
    MOVLW   STATE_DOOR_CLOSE
    MOVWF   E1_STATE
    RETURN
E1_CHK_CLS:
    MOVF    E1_STATE, W
    SUBLW   STATE_DOOR_CLOSE
    BTFSS   STATUS, Z
    RETURN
    BTFSC   E1_SENSORS, 0
    GOTO    E1_DR_DN
    BTFSC   E1_SENSORS, 2
    GOTO    E1_REOP
    BTFSC   E1_SENSORS, 3
    GOTO    E1_REOP
    RETURN
E1_REOP:
    MOVLW   STATE_DOOR_OPEN
    MOVWF   E1_STATE
    MOVLW   DELAY_2SEC
    MOVWF   E1_DOOR_TIMER
    RETURN
E1_DR_DN:
    MOVLW   STATE_IDLE
    MOVWF   E1_STATE
    MOVLW   0x07
    ANDWF   E1_CABIN_REQUESTS, F
    RETURN

HANDLE_E2_DR:
    MOVF    E2_STATE, W
    SUBLW   STATE_DOOR_OPEN
    BTFSS   STATUS, Z
    GOTO    E2_CHK_CLS
    BTFSC   E2_SENSORS, 3
    GOTO    E2_OW
    BTFSC   E2_SENSORS, 2
    GOTO    E2_IR
    MOVF    E2_CABIN_REQUESTS, W
    ANDLW   0x08
    BTFSS   STATUS, Z
    GOTO    E2_KEEP_OP
    MOVF    E2_DOOR_TIMER, F
    BTFSC   STATUS, Z
    GOTO    E2_BGN_CLS
    DECF    E2_DOOR_TIMER, F
    RETURN
E2_OW:
    BSF     PORTE, 1
    MOVLW   DELAY_2SEC
    MOVWF   E2_DOOR_TIMER
    RETURN
E2_IR:
    MOVLW   DELAY_2SEC
    MOVWF   E2_DOOR_TIMER
    RETURN
E2_KEEP_OP:
    MOVLW   DELAY_2SEC
    MOVWF   E2_DOOR_TIMER
    RETURN
E2_BGN_CLS:
    MOVLW   STATE_DOOR_CLOSE
    MOVWF   E2_STATE
    RETURN
E2_CHK_CLS:
    MOVF    E2_STATE, W
    SUBLW   STATE_DOOR_CLOSE
    BTFSS   STATUS, Z
    RETURN
    BTFSC   E2_SENSORS, 0
    GOTO    E2_DR_DN
    BTFSC   E2_SENSORS, 2
    GOTO    E2_REOP
    BTFSC   E2_SENSORS, 3
    GOTO    E2_REOP
    RETURN
E2_REOP:
    MOVLW   STATE_DOOR_OPEN
    MOVWF   E2_STATE
    MOVLW   DELAY_2SEC
    MOVWF   E2_DOOR_TIMER
    RETURN
E2_DR_DN:
    MOVLW   STATE_IDLE
    MOVWF   E2_STATE
    MOVLW   0x07
    ANDWF   E2_CABIN_REQUESTS, F
    RETURN

HANDLE_E3_DR:
    MOVF    E3_STATE, W
    SUBLW   STATE_DOOR_OPEN
    BTFSS   STATUS, Z
    GOTO    E3_CHK_CLS
    BTFSC   E3_SENSORS, 3
    GOTO    E3_OW
    BTFSC   E3_SENSORS, 2
    GOTO    E3_IR
    MOVF    E3_CABIN_REQUESTS, W
    ANDLW   0x08
    BTFSS   STATUS, Z
    GOTO    E3_KEEP_OP
    MOVF    E3_DOOR_TIMER, F
    BTFSC   STATUS, Z
    GOTO    E3_BGN_CLS
    DECF    E3_DOOR_TIMER, F
    RETURN
E3_OW:
    BSF     PORTC, 5
    MOVLW   DELAY_2SEC
    MOVWF   E3_DOOR_TIMER
    RETURN
E3_IR:
    MOVLW   DELAY_2SEC
    MOVWF   E3_DOOR_TIMER
    RETURN
E3_KEEP_OP:
    MOVLW   DELAY_2SEC
    MOVWF   E3_DOOR_TIMER
    RETURN
E3_BGN_CLS:
    MOVLW   STATE_DOOR_CLOSE
    MOVWF   E3_STATE
    RETURN
E3_CHK_CLS:
    MOVF    E3_STATE, W
    SUBLW   STATE_DOOR_CLOSE
    BTFSS   STATUS, Z
    RETURN
    BTFSC   E3_SENSORS, 0
    GOTO    E3_DR_DN
    BTFSC   E3_SENSORS, 2
    GOTO    E3_REOP
    BTFSC   E3_SENSORS, 3
    GOTO    E3_REOP
    RETURN
E3_REOP:
    MOVLW   STATE_DOOR_OPEN
    MOVWF   E3_STATE
    MOVLW   DELAY_2SEC
    MOVWF   E3_DOOR_TIMER
    RETURN
E3_DR_DN:
    MOVLW   STATE_IDLE
    MOVWF   E3_STATE
    MOVLW   0x07
    ANDWF   E3_CABIN_REQUESTS, F
    RETURN

UPDATE_BUZZERS:
    MOVF    E1_BUZZER_TIMER, F
    BTFSC   STATUS, Z
    GOTO    E1_BZ_OFF
    DECF    E1_BUZZER_TIMER, F
    GOTO    CHK_E2_BZ
E1_BZ_OFF:
    BTFSS   E1_SENSORS, 3
    BCF     PORTD, 4
CHK_E2_BZ:
    MOVF    E2_BUZZER_TIMER, F
    BTFSC   STATUS, Z
    GOTO    E2_BZ_OFF
    DECF    E2_BUZZER_TIMER, F
    GOTO    CHK_E3_BZ
E2_BZ_OFF:
    BTFSS   E2_SENSORS, 3
    BCF     PORTE, 1
CHK_E3_BZ:
    MOVF    E3_BUZZER_TIMER, F
    BTFSC   STATUS, Z
    GOTO    E3_BZ_OFF
    DECF    E3_BUZZER_TIMER, F
    RETURN
E3_BZ_OFF:
    BTFSS   E3_SENSORS, 3
    BCF     PORTC, 5
    RETURN

DELAY_50US:
    MOVLW   0x10
    MOVWF   DELAY_COUNT1
DL50_LP:
    NOP
    DECFSZ  DELAY_COUNT1, F
    GOTO    DL50_LP
    RETURN

DELAY_1MS:
    MOVLW   0xC8
    MOVWF   DELAY_COUNT1
DL1M_LP:
    NOP
    NOP
    DECFSZ  DELAY_COUNT1, F
    GOTO    DL1M_LP
    RETURN

DELAY_10MS:
    MOVLW   0x0A
    MOVWF   DELAY_COUNT2
DL10_LP:
    CALL    DELAY_1MS
    DECFSZ  DELAY_COUNT2, F
    GOTO    DL10_LP
    RETURN
    END