    LIST P=16F877A
    #include <P16F877A.INC>
    __CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF
SLAVE_ADDR      EQU 0x22
FLOOR_NUM       EQU 0x02
CMD_UPDATE_LCD  EQU 0x01
CMD_GET_BUTTONS EQU 0x02
STATE_IDLE      EQU 0x00
STATE_UP        EQU 0x01
STATE_DOWN      EQU 0x02
STATE_DOOR_OPEN EQU 0x03
LCD_CLEAR       EQU 0x01
LCD_HOME        EQU 0x02
LCD_ENTRY_MODE  EQU 0x06
LCD_DISPLAY_ON  EQU 0x0C
LCD_FUNCTION_4B EQU 0x28
LCD_LINE1       EQU 0x80
LCD_LINE2       EQU 0xC0
#define PV_UP_BTN       PORTB, 0
#define PV_DN_BTN       PORTB, 1
#define ST_UP_BTN       PORTB, 2
#define ST_DN_BTN       PORTB, 3
#define KEY_ENABLE      PORTB, 4
    CBLOCK 0x20
        BUTTON_STATE
        BUTTON_DEBOUNCE
        I2C_STATE
        I2C_COMMAND
        I2C_RX_DATA
        I2C_TX_DATA
        I2C_BYTE_COUNT
        E1_STATE
        E1_FLOOR
        E1_DIRECTION
        E2_STATE
        E2_FLOOR
        E2_DIRECTION
        E3_STATE
        E3_FLOOR
        E3_DIRECTION
        LCD_TEMP
        LCD_DATA
        LCD_CURRENT
        TEMP_REG
        TEMP_REG2
        DELAY_COUNT1
        DELAY_COUNT2
        DELAY_COUNT3
        LOOP_COUNT
        STR_INDEX
        CHAR_TEMP
    ENDC
    ORG 0x0000
    GOTO    MAIN_INIT
    ORG 0x0004
    GOTO    ISR_HANDLER

ISR_HANDLER:
    MOVWF   TEMP_REG
    SWAPF   STATUS, W
    MOVWF   TEMP_REG2
    BTFSC   PIR1, SSPIF
    CALL    I2C_SLAVE_ISR
    BCF     PIR1, SSPIF
    SWAPF   TEMP_REG2, W
    MOVWF   STATUS
    SWAPF   TEMP_REG, F
    SWAPF   TEMP_REG, W
    RETFIE

I2C_SLAVE_ISR:
    BSF     STATUS, RP0
    BCF     STATUS, RP1
    BTFSC   SSPSTAT, R_W
    GOTO    I2C_SLAVE_READ
    BTFSC   SSPSTAT, D_A
    GOTO    I2C_SLAVE_DATA_RX
    BCF     STATUS, RP0
    MOVF    SSPBUF, W
    CLRF    I2C_BYTE_COUNT
    BSF     SSPCON, CKP
    RETURN

I2C_SLAVE_DATA_RX:
    BCF     STATUS, RP0
    MOVF    SSPBUF, W
    MOVF    I2C_BYTE_COUNT, F
    BTFSS   STATUS, Z
    GOTO    I2C_RX_DATA_BYTE
    MOVWF   I2C_COMMAND
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

I2C_RX_DATA_BYTE:
    MOVF    I2C_COMMAND, W
    SUBLW   CMD_UPDATE_LCD
    BTFSC   STATUS, Z
    GOTO    I2C_RX_LCD_DATA
    BSF     SSPCON, CKP
    RETURN

I2C_RX_LCD_DATA:
    MOVF    I2C_BYTE_COUNT, W
    SUBLW   0x01
    BTFSC   STATUS, Z
    GOTO    RX_E1_STATE
    MOVF    I2C_BYTE_COUNT, W
    SUBLW   0x02
    BTFSC   STATUS, Z
    GOTO    RX_E1_FLOOR
    MOVF    I2C_BYTE_COUNT, W
    SUBLW   0x03
    BTFSC   STATUS, Z
    GOTO    RX_E1_DIR
    MOVF    I2C_BYTE_COUNT, W
    SUBLW   0x04
    BTFSC   STATUS, Z
    GOTO    RX_E2_STATE
    MOVF    I2C_BYTE_COUNT, W
    SUBLW   0x05
    BTFSC   STATUS, Z
    GOTO    RX_E2_FLOOR
    MOVF    I2C_BYTE_COUNT, W
    SUBLW   0x06
    BTFSC   STATUS, Z
    GOTO    RX_E2_DIR
    MOVF    I2C_BYTE_COUNT, W
    SUBLW   0x07
    BTFSC   STATUS, Z
    GOTO    RX_E3_STATE
    MOVF    I2C_BYTE_COUNT, W
    SUBLW   0x08
    BTFSC   STATUS, Z
    GOTO    RX_E3_FLOOR
    MOVF    I2C_BYTE_COUNT, W
    SUBLW   0x09
    BTFSC   STATUS, Z
    GOTO    RX_E3_DIR
    BSF     SSPCON, CKP
    RETURN

RX_E1_STATE:
    MOVF    SSPBUF, W
    MOVWF   E1_STATE
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

RX_E1_FLOOR:
    MOVF    SSPBUF, W
    MOVWF   E1_FLOOR
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

RX_E1_DIR:
    MOVF    SSPBUF, W
    MOVWF   E1_DIRECTION
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

RX_E2_STATE:
    MOVF    SSPBUF, W
    MOVWF   E2_STATE
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

RX_E2_FLOOR:
    MOVF    SSPBUF, W
    MOVWF   E2_FLOOR
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

RX_E2_DIR:
    MOVF    SSPBUF, W
    MOVWF   E2_DIRECTION
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

RX_E3_STATE:
    MOVF    SSPBUF, W
    MOVWF   E3_STATE
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

RX_E3_FLOOR:
    MOVF    SSPBUF, W
    MOVWF   E3_FLOOR
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

RX_E3_DIR:
    MOVF    SSPBUF, W
    MOVWF   E3_DIRECTION
    INCF    I2C_BYTE_COUNT, F
    BSF     SSPCON, CKP
    RETURN

I2C_SLAVE_READ:
    BCF     STATUS, RP0
    MOVF    I2C_COMMAND, W
    SUBLW   CMD_GET_BUTTONS
    BTFSS   STATUS, Z
    GOTO    I2C_SEND_ZERO
    MOVF    BUTTON_STATE, W
    MOVWF   SSPBUF
    BSF     SSPCON, CKP
    RETURN

I2C_SEND_ZERO:
    CLRF    SSPBUF
    BSF     SSPCON, CKP
    RETURN

MAIN_INIT:
    BSF     STATUS, RP0
    BCF     STATUS, RP1
    MOVLW   0xFF
    MOVWF   TRISB
    BCF     OPTION_REG, 7
    MOVLW   0x18
    MOVWF   TRISC
    MOVLW   0x00
    MOVWF   TRISD
    MOVLW   SLAVE_ADDR << 1
    MOVWF   SSPADD
    MOVLW   0x80
    MOVWF   SSPSTAT
    BSF     PIE1, SSPIE
    BCF     STATUS, RP0
    MOVLW   0x36
    MOVWF   SSPCON
    CLRF    PORTA
    CLRF    PORTB
    CLRF    PORTC
    CLRF    PORTD
    CLRF    BUTTON_STATE
    CLRF    I2C_STATE
    CLRF    I2C_COMMAND
    CLRF    I2C_BYTE_COUNT
    CLRF    E1_STATE
    CLRF    E1_FLOOR
    CLRF    E1_DIRECTION
    CLRF    E2_STATE
    CLRF    E2_FLOOR
    CLRF    E2_DIRECTION
    CLRF    E3_STATE
    CLRF    E3_FLOOR
    CLRF    E3_DIRECTION
    CALL    LCD_INIT_ALL
    BSF     INTCON, GIE
    BSF     INTCON, PEIE




MAIN_LOOP:
    CALL    READ_BUTTONS
    CALL    UPDATE_ALL_LCDS
    CALL    DELAY_50MS
    GOTO    MAIN_LOOP




READ_BUTTONS:
    CLRF    BUTTON_STATE
    BTFSS   PORTB, 0
    BSF     BUTTON_STATE, 0
    #if FLOOR_NUM != 0x00
    BTFSS   PORTB, 1
    BSF     BUTTON_STATE, 1
    #endif
    #if FLOOR_NUM != 0x02
    BTFSS   PORTB, 4
    GOTO    NO_STAFF_UP
    BTFSS   PORTB, 2
    BSF     BUTTON_STATE, 2
NO_STAFF_UP:
    #endif
    #if FLOOR_NUM != 0x00
    BTFSS   PORTB, 4
    GOTO    NO_STAFF_DN
    BTFSS   PORTB, 3
    BSF     BUTTON_STATE, 3
NO_STAFF_DN:
    #endif
    BTFSS   PORTB, 4
    BSF     BUTTON_STATE, 4
    #if FLOOR_NUM == 0x00
    BCF     BUTTON_STATE, 1
    BCF     BUTTON_STATE, 3
    #endif
    #if FLOOR_NUM == 0x02
    BCF     BUTTON_STATE, 0
    BCF     BUTTON_STATE, 2
    #endif
    RETURN




LCD_INIT_ALL:
    MOVLW   0x01
    MOVWF   LCD_CURRENT
    CALL    LCD_INIT
    MOVLW   0x02
    MOVWF   LCD_CURRENT
    CALL    LCD_INIT
    MOVLW   0x03
    MOVWF   LCD_CURRENT
    CALL    LCD_INIT
    RETURN

LCD_INIT:
    CALL    DELAY_50MS
    MOVLW   0x03
    CALL    LCD_SEND_NIBBLE_CMD
    CALL    DELAY_5MS
    MOVLW   0x03
    CALL    LCD_SEND_NIBBLE_CMD
    CALL    DELAY_1MS
    MOVLW   0x03
    CALL    LCD_SEND_NIBBLE_CMD
    CALL    DELAY_1MS
    MOVLW   0x02
    CALL    LCD_SEND_NIBBLE_CMD
    CALL    DELAY_1MS
    MOVLW   LCD_FUNCTION_4B
    CALL    LCD_COMMAND
    MOVLW   LCD_DISPLAY_ON
    CALL    LCD_COMMAND
    MOVLW   LCD_CLEAR
    CALL    LCD_COMMAND
    CALL    DELAY_5MS
    MOVLW   LCD_ENTRY_MODE
    CALL    LCD_COMMAND
    RETURN

LCD_ENABLE_PULSE:
    MOVF    LCD_CURRENT, W
    SUBLW   0x01
    BTFSC   STATUS, Z
    BSF     PORTC, 1
    MOVF    LCD_CURRENT, W
    SUBLW   0x02
    BTFSC   STATUS, Z
    BSF     PORTC, 2
    MOVF    LCD_CURRENT, W
    SUBLW   0x03
    BTFSC   STATUS, Z
    BSF     PORTC, 5
    NOP
    NOP
    BCF     PORTC, 1
    BCF     PORTC, 2
    BCF     PORTC, 5
    RETURN

LCD_SEND_NIBBLE_CMD:
    BCF     PORTC, 0
    MOVWF   LCD_TEMP
    SWAPF   LCD_TEMP, W
    ANDLW   0xF0
    MOVWF   PORTD
    CALL    LCD_ENABLE_PULSE
    RETURN

LCD_COMMAND:
    MOVWF   LCD_DATA
    BCF     PORTC, 0
    MOVF    LCD_DATA, W
    ANDLW   0xF0
    MOVWF   PORTD
    CALL    LCD_ENABLE_PULSE
    SWAPF   LCD_DATA, W
    ANDLW   0xF0
    MOVWF   PORTD
    CALL    LCD_ENABLE_PULSE
    CALL    DELAY_1MS
    RETURN

LCD_WRITE_CHAR:
    MOVWF   LCD_DATA
    BSF     PORTC, 0
    MOVF    LCD_DATA, W
    ANDLW   0xF0
    MOVWF   PORTD
    CALL    LCD_ENABLE_PULSE
    SWAPF   LCD_DATA, W
    ANDLW   0xF0
    MOVWF   PORTD
    CALL    LCD_ENABLE_PULSE
    BCF     PORTC, 0
    CALL    DELAY_1MS
    RETURN

UPDATE_ALL_LCDS:
    MOVLW   0x01
    MOVWF   LCD_CURRENT
    MOVF    E1_STATE, W
    MOVWF   TEMP_REG
    MOVF    E1_FLOOR, W
    MOVWF   TEMP_REG2
    MOVF    E1_DIRECTION, W
    CALL    UPDATE_SINGLE_LCD
    MOVLW   0x02
    MOVWF   LCD_CURRENT
    MOVF    E2_STATE, W
    MOVWF   TEMP_REG
    MOVF    E2_FLOOR, W
    MOVWF   TEMP_REG2
    MOVF    E2_DIRECTION, W
    CALL    UPDATE_SINGLE_LCD
    MOVLW   0x03
    MOVWF   LCD_CURRENT
    MOVF    E3_STATE, W
    MOVWF   TEMP_REG
    MOVF    E3_FLOOR, W
    MOVWF   TEMP_REG2
    MOVF    E3_DIRECTION, W
    CALL    UPDATE_SINGLE_LCD
    RETURN

UPDATE_SINGLE_LCD:
    MOVWF   CHAR_TEMP
    MOVLW   LCD_LINE1
    CALL    LCD_COMMAND
    MOVLW   'E'
    CALL    LCD_WRITE_CHAR
    MOVLW   'l'
    CALL    LCD_WRITE_CHAR
    MOVLW   'e'
    CALL    LCD_WRITE_CHAR
    MOVLW   'v'
    CALL    LCD_WRITE_CHAR
    MOVLW   'a'
    CALL    LCD_WRITE_CHAR
    MOVLW   't'
    CALL    LCD_WRITE_CHAR
    MOVLW   'o'
    CALL    LCD_WRITE_CHAR
    MOVLW   'r'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVF    LCD_CURRENT, W
    ADDLW   '0'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   LCD_LINE2
    CALL    LCD_COMMAND
    MOVF    TEMP_REG, W
    SUBLW   STATE_IDLE
    BTFSC   STATUS, Z
    GOTO    PRINT_IDLE
    MOVF    TEMP_REG, W
    SUBLW   STATE_DOOR_OPEN
    BTFSC   STATUS, Z
    GOTO    PRINT_DOOR_OPEN
    MOVLW   'L'
    CALL    LCD_WRITE_CHAR
    MOVLW   'e'
    CALL    LCD_WRITE_CHAR
    MOVLW   'v'
    CALL    LCD_WRITE_CHAR
    MOVLW   'e'
    CALL    LCD_WRITE_CHAR
    MOVLW   'l'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVF    TEMP_REG2, W
    BTFSC   STATUS, Z
    GOTO    PRINT_GF
    SUBLW   0x01
    BTFSC   STATUS, Z
    GOTO    PRINT_F1
    GOTO    PRINT_F2

PRINT_GF:
    MOVLW   'G'
    CALL    LCD_WRITE_CHAR
    MOVLW   'F'
    CALL    LCD_WRITE_CHAR
    GOTO    PRINT_DIRECTION

PRINT_F1:
    MOVLW   '1'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    GOTO    PRINT_DIRECTION

PRINT_F2:
    MOVLW   '2'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    GOTO    PRINT_DIRECTION

PRINT_DIRECTION:
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   '-'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVF    CHAR_TEMP, W
    SUBLW   STATE_UP
    BTFSC   STATUS, Z
    GOTO    PRINT_UP
    MOVF    CHAR_TEMP, W
    SUBLW   STATE_DOWN
    BTFSC   STATUS, Z
    GOTO    PRINT_DOWN
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    RETURN

PRINT_UP:
    MOVLW   'U'
    CALL    LCD_WRITE_CHAR
    MOVLW   'P'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    RETURN

PRINT_DOWN:
    MOVLW   'D'
    CALL    LCD_WRITE_CHAR
    MOVLW   'O'
    CALL    LCD_WRITE_CHAR
    MOVLW   'W'
    CALL    LCD_WRITE_CHAR
    MOVLW   'N'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    RETURN

PRINT_IDLE:
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   'I'
    CALL    LCD_WRITE_CHAR
    MOVLW   'D'
    CALL    LCD_WRITE_CHAR
    MOVLW   'L'
    CALL    LCD_WRITE_CHAR
    MOVLW   'E'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    RETURN

PRINT_DOOR_OPEN:
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   'D'
    CALL    LCD_WRITE_CHAR
    MOVLW   'O'
    CALL    LCD_WRITE_CHAR
    MOVLW   'O'
    CALL    LCD_WRITE_CHAR
    MOVLW   'R'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   'O'
    CALL    LCD_WRITE_CHAR
    MOVLW   'P'
    CALL    LCD_WRITE_CHAR
    MOVLW   'E'
    CALL    LCD_WRITE_CHAR
    MOVLW   'N'
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    MOVLW   ' '
    CALL    LCD_WRITE_CHAR
    RETURN

DELAY_1MS:
    MOVLW   0xC8
    MOVWF   DELAY_COUNT1
DELAY_1MS_LOOP:
    NOP
    NOP
    DECFSZ  DELAY_COUNT1, F
    GOTO    DELAY_1MS_LOOP
    RETURN

DELAY_5MS:
    MOVLW   0x05
    MOVWF   DELAY_COUNT2
DELAY_5MS_LOOP:
    CALL    DELAY_1MS
    DECFSZ  DELAY_COUNT2, F
    GOTO    DELAY_5MS_LOOP
    RETURN

DELAY_50MS:
    MOVLW   0x32
    MOVWF   DELAY_COUNT2
DELAY_50MS_LOOP:
    CALL    DELAY_1MS
    DECFSZ  DELAY_COUNT2, F
    GOTO    DELAY_50MS_LOOP
    RETURN
    END